# Generated by Django 3.2.5 on 2021-07-14 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_product_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AlterField(
            model_name='product',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.kind', verbose_name='种类'),
        ),
    ]
