# Generated by Django 3.2.5 on 2021-07-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('河北省', '河北省'), ('山西省', '山西省'), ('辽宁省', '辽宁省'), ('吉林省', '吉林省'), ('黑龙江省', '黑龙江省'), ('江苏省', '江苏省'), ('浙江省', '浙江省'), ('安徽省', '安徽省'), ('福建省', '福建省'), ('江西省', '江西省'), ('山东省', '山东省'), ('河南省', '河南省'), ('湖北省', '湖北省'), ('湖南省', '湖南省'), ('广东省', '广东省'), ('海南省', '海南省'), ('四川省', '四川省'), ('贵州省', '贵州省'), ('云南省', '云南省'), ('陕西省', '陕西省'), ('甘肃省', '甘肃省'), ('青海省', '青海省'), ('台湾省', '台湾省'), ('内蒙古自治区', '内蒙古自治区'), ('西藏自治区', '西藏自治区'), ('宁夏回族自治区', '宁夏回族自治区'), ('新疆维吾尔自治区', '新疆维吾尔自治区'), ('北京市', '北京市'), ('天津市', '天津市'), ('上海市', '上海市'), ('重庆市', '重庆市')], max_length=20, verbose_name='省份'),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', '已完成'), ('Paked', '已打包'), ('On The Way', '已发货'), ('Delivered', '已送达'), ('Cancel', '已取消'), ('pending', '受理中')], default='pending', max_length=50),
        ),
    ]
