# Generated by Django 3.2.5 on 2021-07-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_auto_20210714_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('已完成', '已完成'), ('已打包', '已打包'), ('已发货', '已发货'), ('已送达', '已送达'), ('已取消', '已取消'), ('受理中', '受理中')], default='受理中', max_length=50),
        ),
    ]
