# Generated by Django 3.2.5 on 2021-07-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_alter_orderplaced_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('已完成', '已完成'), ('已打包', '已打包'), ('已发货', '已发货'), ('已送达', '已送达'), ('已取消', '已取消'), ('受理中', '受理中')], default='受理中', max_length=50, verbose_name='订单状态'),
        ),
        migrations.DeleteModel(
            name='SHOPS',
        ),
    ]
